echo Resetting DHCPCD config metric to prefer Cellular interface...
  cp /etc/dhcpcd-cell.conf /etc/dhcpcd.conf
echo Restarting DHCP Client Daemon...
sudo  systemctl restart dhcpcd
echo Waiting 4 seconds for DHCP leases to renew on Cellular interface...
sleep 4
echo Done. Route below should reflect preferred default gateways.
route -n
